/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiContacts: typeof import('~icons/mdi/contacts')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiShapeCirclePlus: typeof import('~icons/mdi/shape-circle-plus')['default']
    IMdiSpace: typeof import('~icons/mdi/space')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    IMdiTodo: typeof import('~icons/mdi/todo')['default']
    IMdiTooltipEdit: typeof import('~icons/mdi/tooltip-edit')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
